mysite/mysite/urls.py
#This is accessed first, because it is pointed to in the root_urlconf setting.


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    #each URL pattern has 2 or more arguments. The first argument is a regex
    #django starts at the first regular expression and makes its way down this
    #list looking for matches to the requested site by the browser
    #The second argument is the view function that is called when there is a regex
    #match. Common third agument is just the name
######url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^getData/',include('getData.urls',namespace="getData")),   
    url(r'^polls/', include('polls.urls',namespace="polls")),  
    #the namespace makes sure that search in polls subdirectories only
    url(r'^admin/', include(admin.site.urls)), 

#the include function basically appends other, specified url.py files
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


#This defines a class known as Question which inherits
#from models.Model 
class Question(models.Model):

	#Ok, now lets give a couple of variables to this
	#this
	question_text = models.CharField(max_length=200)     #To do. Look up a bunch of different models
	pub_date = models.DateTimeField('date published')
	
	#Ok, now lets give this class a couple of methods
	def __unicode__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	was_published_recently.admin_order_field = 'pub_date'   #ok, lets give it a thing to order by
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
	question = models.ForeignKey(Question)   #not quite sure what this ForeignKey thing is...
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from .models import Question, Choice

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" name="poll_form">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" name="Vote" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
	<!-- So here polls:detail is the namespace tag. Urls reference to views and so here
	     am referencing the view detail which is inside polls-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>  
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>