mysite/getData/urls.py
from django.conf.urls import url,  patterns, include
from django.contrib import admin

from . import views


admin.autodiscover()


urlpatterns = [
	url(r'^$',views.boxes,name='boxes'),
	url(r'^(?P<box_nr>[0-9]+)/$',views.box_info,name='box_info'),
	url(r'^(?P<box_nr>[0-9]+)/get_box_data/$',views.get_box_data,name='get_box_data'),
	url(r'^(?P<box_nr>[0-9]+)/set_mouse_ID/$', views.set_mouse_ID, name='set_mouse_ID'),
	url(r'^(?P<box_nr>[0-9]+)/write_mouse_ID/$', views.write_mouse_ID, name='write_mouse_ID'),
	url(r'^(?P<box_nr>[0-9]+)/set_mouse_task/$', views.set_mouse_task, name='set_mouse_task'),
	url(r'^(?P<box_nr>[0-9]+)/write_mouse_task/$', views.write_mouse_task, name='write_mouse_task'),
	url(r'^(?P<box_nr>[0-9]+)/get_PiData/$', views.get_PiData, name='get_PiData'),
	url(r'^(?P<box_nr>[0-9]+)/write_PiData/$', views.write_PiData, name='write_PiData'),
	url(r'^set_num_boxes/$', views.set_num_boxes, name='set_num_boxes'),
	url(r'^write_num_boxes/$', views.write_num_boxes, name='write_num_boxes'),
	url(r'^download_data/$', views.download_data, name='download_data'),
	url(r'^download_data/(?P<mouse_ID>[^/]{0,20})/$', views.list_mousewise, name='list_mousewise'),
	url(r'^download_data/(?P<mouse_ID>[^/]{0,20})/(?P<fileName>.*)/$', views.download_mousewise, name='download_mousewise'),

	url(r'^(?P<box_nr>[0-9]+)/(?P<isOnline>True|False|0|1)/upload_new_task/$', views.upload_new_task, name='upload_new_task'),

]

mysite/mysite/urls.py
#This is accessed first, because it is pointed to in the root_urlconf setting.


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    #each URL pattern has 2 or more arguments. The first argument is a regex
    #django starts at the first regular expression and makes its way down this
    #list looking for matches to the requested site by the browser
    #The second argument is the view function that is called when there is a regex
    #match. Common third agument is just the name
######url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^getData/',include('getData.urls',namespace="getData")),   
    url(r'^polls/', include('polls.urls',namespace="polls")),  
    #the namespace makes sure that search in polls subdirectories only
    url(r'^admin/', include(admin.site.urls)), 

#the include function basically appends other, specified url.py files
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/getData/models.py
from django.db import models


class box(models.Model):

	box_nr = models.CharField(max_length=4)
	box_type = models.CharField(max_length=200)
	

	def __unicode__(self):
		return self.box_nr
	


	"""
	def getMouseID
	def getTask
	def setTask
	def WaterIntake
	"""

mysite/getData/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

mysite/getData/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
#________________
from django.utils.timezone import utc
import datetime


#________________
import os, errno
import csv
import os
import re
import ast
import subprocess
from multiprocessing.dummy import Pool
import zipfile


#________________________________________________________________________________________________________








def boxes(request):
 	numBoxes = get_num_boxes()

	box_connected = ping_boxes(numBoxes)


	mouseIDs = [get_mouse_ID(box_nr) for box_nr in range(numBoxes)]
	
	context = {'boxs_and_IDs':zip(range(numBoxes), mouseIDs,box_connected)}
	#context = {'box_list': range(numBoxes),'mouseIDs':mouseIDso
	# ideally, we want to expand this bit to include which
	# which mouse is in there and what task it is performing
	# add this as things to the context thing
	return render(request,'getData/boxes.html',context)


def box_info(request, box_nr):

	box_connected = ping_box(box_nr)
	#box_connected = is_online=='True'
	mouse_ID = get_mouse_ID(box_nr)

	task_schedule = get_mouse_task_schedule(box_nr)

	try:
		tasks, durations,duration_str = parse_task_schedule(task_schedule)



	except:
		tasks = []
		durations = []
		duration_str = []



	try:
		time_received = datetime.datetime.strptime(  re.findall(r'.*received(.*)',task_schedule)[0] , '%Y-%m-%d %H:%M:%S.%f')
		time_elapsed_tdelta = datetime.datetime.now() - time_received
		time_elapsed = time_parser( time_elapsed_tdelta.total_seconds() )
		
		cumsum_TL = []
		acc = 0
		for i in durations:
	    		acc += 1
	    		cumsum_TL.append(acc)
			task_completions = [time_elapsed_tdelta.total_seconds()>i for i in cumsum_TL]
		
	except IndexError:
		time_received = 'Not accessed yet'
		time_elapsed = []
	if len(tasks)==1:
		task_completions = [False]
		total_dur = time_parser(durations[0])
	else:
		task_completions = [i<-1 for i in range(len(tasks))]
		total_dur = time_parser(sum(durations))
		






	context = {'box_nr': box_nr,'mouse_ID':mouse_ID,
		   'task_names_and_durations': zip(tasks,duration_str,task_completions),
		   'total_duration': total_dur,
		   'time_elapsed': time_elapsed,
		   'isOnline':box_connected}


	return render(request,'getData/box_info.html',context)



#________________________________________________________________________________________________________
def set_mouse_ID(request,box_nr):
	
	context = {'box_nr': box_nr}
	return render(request, 'getData/set_mouse_ID.html',context)

	
def write_mouse_ID(request,box_nr):

	openstr = '/home/rastamouse/Documents/Data/mousecagemaps/' + 'box_' + str(box_nr)

	f = open(openstr,'w+b')
	f.write(str(request.POST['mouseID']))
	f.close()
	return HttpResponseRedirect(reverse('getData:box_info',args=(box_nr,)))
	

#________________________________________________________________________________________________________

def set_mouse_task(request,box_nr):

	if request.method == 'GET':
		ssh_dest =   r'pi@192.168.' + str(100 + int(box_nr))
		p = subprocess.Popen(["ssh", "%s" % ssh_dest, "ls /home/pi/behaviour_scripts"],
				      shell=False, stdout=subprocess.PIPE, stderr = subprocess.PIPE)
		tasks = p.stdout.readlines()

		context = {'box_nr': box_nr,'taskList':tasks}
		return render(request, 'getData/set_mouse_task.html',context)
	

	if request.method == 'POST':
		ssh_dest =   r'pi@192.168.' + str(100 + int(box_nr))
		p = subprocess.Popen(["ssh", "%s" % ssh_dest, "python /home/pi/behaviour_scripts/" + request.POST.get('task_name')],
				      shell=False, stdout=subprocess.PIPE, stderr = subprocess.PIPE)
		retrnTxt = p.stdout.readlines()
		if (retrnTxt[0]=='hello world\n'):
			openstr = '/home/rastamouse/Documents/Data/cage_tasks/' + 'box_' + str(box_nr)

			f = open(openstr,'w+b')
			task_schedule = str(request.POST['task_name'])
			f.write(task_schedule)
			f.close()
			return HttpResponseRedirect(reverse('getData:box_info',args=(box_nr,)))
	

def write_mouse_task(request,box_nr):

	openstr = '/home/rastamouse/Documents/Data/cage_tasks/' + 'box_' + str(box_nr)

	f = open(openstr,'w+b')

	task_schedule = str(  [ request.POST['task_name'], request.POST['duration']  ] )
	f.write(task_schedule)
	f.close()
	return HttpResponseRedirect(reverse('getData:box_info',args=(box_nr,)))

	
#________________________________________________________________________________________________________


def set_num_boxes(request):
	return render(request,'getData/set_num_boxes.html')


	
def write_num_boxes(request):
	f = open('/home/rastamouse/Documents/Data/numboxes','w+b')
	toWrite = 'number_of_boxes='+ str(request.POST['newNumBoxes'])
	f.write(toWrite)
	f.close()

	return HttpResponseRedirect(reverse('getData:boxes'))

#________________________________________________________________________________________________________

def get_PiData(request,box_nr):
	context = {'box_nr': box_nr}
	return render(request,'getData/store_data_form.html',context)



def write_PiData(request,box_nr):
	
	base_path = '/home/rastamouse/Documents/Data/'

	#######
	#box_nr = request.POST['box_nr']
	openstr_MouseID = '/home/rastamouse/Documents/Data/mousecagemaps/' + 'box_' + str(box_nr)
	f = open(openstr_MouseID,'r')
	mouse_ID = f.read()
	######
	openstr_Task = '/home/rastamouse/Documents/Data/cage_tasks/' + 'box_' + str(box_nr)
	f = open(openstr_Task,'r')
	task_name = f.read()
	########
	
	path = base_path + mouse_ID + task_name

	data =request.POST['piData'].split(',')

	if os.path.isdir(path):
		pass
	else:
		mkdir_p(path)


	with open( path+ r'/' 'test.csv','a') as results:
		writer = csv.writer(results,dialect='excel')
		writer.writerow(data)



	return  HttpResponseRedirect(reverse('getData:box_info',args=(box_nr,)))

#________________________________________________________________________________________________________
def get_box_data(request,box_nr):

	task_schedule = get_mouse_task_schedule(box_nr, True)
	
	context = {'box_nr':box_nr}
	return render(request, 'getData/get_box_data.html',context)



#________________________________________________________________________________________________________

def download_data(request):


	base_filepath = '/home/rastamouse/Documents/Data/behaviour_data/'


	if request.method == 'GET':

		mouse_dirs = os.listdir(base_filepath+'mousewise')
		context = {'mouse_dirs': mouse_dirs}

		return render(request, 'getData/choose_box.html',context)
		

	

	


	if request.method == 'POST':
		
		path = base_filepath + request.POST.get('Mouse_ID')
		zipPath = base_filepath + r'zipfiles/' + request.POST.get('Mouse_ID') + r'.zip'
		zipf = zipfile.ZipFile(zipPath, 'w')


    		for root, dirs, files in os.walk(path):
       			 for file in files:
           			zipf.write(os.path.join(root, file))


		response = HttpResponse(zipf, content_type='application/zip')
		response['Content-Disposition'] = "attachment; filename=request.POST.get('Mouse_ID')"

		

		return response

	
	#os.path.isfile('/home/rastamouse/Documents/Data/behaviour_data')




def list_mousewise(request, mouse_ID):

	base_filepath = '/home/rastamouse/Documents/Data/behaviour_data/mousewise/'
	mouseFiles = os.listdir(base_filepath + mouse_ID)
	context = {'mouseFiles': mouseFiles,'mouse_ID': mouse_ID}
	return render(request,'getData/list_mousewise.html',context)



def download_mousewise(request, mouse_ID, fileName):

	base_filepath = '/home/rastamouse/Documents/Data/behaviour_data/mousewise/'
	filepath = base_filepath + mouse_ID + r'/' + fileName

	response = HttpResponse(open(filepath))
	response['Content-Disposition'] = "attachment; filename=test.txt"

	return response
	

#________________________________________________________________________________________________________


def upload_new_task(request,box_nr,isOnline):
    # Handle file upload
	if request.method == 'POST':
        
		sentTask = request.FILES['sentFile']
		with open('/home/rastamouse/' + sentTask.name, 'wb+') as destination:
			for chunk in sentTask.chunks():
            			destination.write(chunk)

		scp_dest =   r'192.168.' + str(100 + int(box_nr))
		os.system('scp ' + '/home/rastamouse/' + sentTask.name + ' pi@' + scp_dest + ':/home/pi/behaviour_scripts/' + sentTask.name)

            	# Redirect to the document list after POST
		return HttpResponseRedirect(reverse('getData:boxes'))
	else:


    		# Render list page with the documents and the form
		return render(request,'getData/upload_new_task.html',context={'isOnline':isOnline=='1'})

#______________________________________




""" Below are Helper functions for the views """



#_______________________________________
def get_num_boxes():
	f = open('/home/rastamouse/Documents/Data/numboxes')
	return int(re.findall(r'number_of_boxes=([0-9]+)',f.read())[0])



#_________________________________________________________________________________________________________________
def parse_task_schedule(task_schedule):

	if task_schedule!='':
		a = re.findall(r'(.*)received.*',task_schedule)
		if a==[]:
			a = task_schedule
		else:
			a = a[0]
		
		aa = ast.literal_eval(a) 
		try:

			durations = ast.literal_eval(aa[1])
			tasks = ast.literal_eval(aa[0])
			duration_str = [time_parser(dur) for dur in durations]
			#tasks = ast.literal_eval(aap)

		except:
			tasks = [str(aa[0])]
			durations = [int(aa[1])]
			duration_str = [time_parser(durations[0])]
	
	return tasks, durations,duration_str


#_________________________________________________________________________________________________________________

def time_parser(duration):

	m,s = divmod(duration,60)
	h,m = divmod(m,60)
	d,h = divmod(h,24)	

	timeStr = ("%ddays %dh:%dm:%ds" %(d,h,m,s) ) 
	return timeStr


#_________________________________________________________________________________________________________________
def get_mouse_ID(box_nr):

	openstr_MouseID = '/home/rastamouse/Documents/Data/mousecagemaps/' + 'box_' + str(box_nr)
	
	try:
	

mysite/getData/templates/getData/box_info.html
<h1> Box {{box_nr}} </h1>

{% if isOnline %}
 <font color="green">The box is online!</font> 
{% endif %}

{% if not isOnline %}
 <font color="red">The box is offline</font> 
{% endif %}
<br>



<p> <a href="{% url 'getData:set_mouse_ID' box_nr %}" > Change the ID of the Mouse in this cage
 </a> </p> 
Current id is: {{mouse_ID}}
<br>
<br>
<br>
<p> <a href="/getData/{{box_nr}}/set_mouse_task/"> Change the task schedule for this cage </a> </p>
The Current Task Schedule is:
<br>
<br>
{% for task, duration, completed in task_names_and_durations %}
	
<li> Task: {{task}} , duration: {{duration}},
<br> Completed: {{completed}}

<br>
<br>
{% endfor %}
<br>
<br>

Total scheduled run time is {{total_duration}}
<br>
<br>
{{time_elapsed}} have elapsed
<br>
<br>
<br>
<p> <a href="/getData/{{box_nr}}/{{isOnline}}/upload_new_task"> Upload New Task to Server and Cage
 </a> </p> 

mysite/getData/templates/getData/boxes.html
<h1> Here are a bunch of boxes </h1>


<ul>


<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: center;
}
</style>

<body>
<br>
<br>
<h2> Control Boxes and Update Info </h2>
<table border="1" style="width:100%">

  <tr>
    <th>Cage Number</th>
    <th>Mouse ID</th>
    <th>Status</th>
  </tr>

{% for box, mouseID,isOnline in boxs_and_IDs %}
	<tr>
		<td><a href="/getData/{{box}}/"> Box Nr: {{box}} </a> </td>
		<td> {{mouseID}}  </td>
		{% if isOnline %}
		<td>  <font color="green">online!</font>  </td>
		{% endif %}

		{% if not isOnline %}
		<td>  <font color="red">offline</font>  </td>
		{% endif %}
 <br>
	</tr>
{% endfor %}

</body>


</ul>

</table>

<br>
<br>
<br>
<a href="/getData/download_data/" > <h2> <font color="black" >Download Data Mouse_Wise </font> </h2>

mysite/getData/templates/getData/choose_box.html
<html>

<h2> Access to Individual Data Files, sorted by Mouse </h2>


{% for mouse_dir in mouse_dirs %}
	<li> <a href="/getData/download_data/{{mouse_dir}}/"> {{mouse_dir}} </a>   </li>
{% endfor %}

<h2> Download entire mouse training dataset as zip file </h2>

	<form action="{% url 'getData:download_data' %}" method="post"> 
	{% csrf_token %}
	  <select name="Mouse_ID">

	    {% for mouse_name in mouse_dirs %}
	    <option value={{mouse_name}}> {{mouse_name}} </option>
	    {% endfor %}
	  </select>
	  <input type="submit" value="Download">
	</form> 



</html>

mysite/getData/templates/getData/get_box_data.html
<h1> Yoyo wassup?!  you are looking at box number {{box_nr}} </h1>

mysite/getData/templates/getData/list_mousewise.html
<h2> Training Data for {{mouse_ID}} </h2>


{% for file in mouseFiles %}
	<li> <a href="/getData/download_data/{{mouse_ID}}/{{file}}/" > {{file}} </li>
{% endfor %}

mysite/getData/templates/getData/set_mouse_ID.html
<form action="{% url 'getData:write_mouse_ID' box_nr %}" method="post">
{% csrf_token %}
    Mouse ID in Cage {{box_nr}}: <input type="text" name="mouseID" "value=0" />
		    <input type="submit" value="submit" />
</form>

mysite/getData/templates/getData/set_mouse_task.html
<form action="{% url 'getData:set_mouse_task' box_nr %}" method="post"> 
	{% csrf_token %}
	  <select name="task_name">

	    {% for task in taskList %}
	    <option value={{task}}> {{task}} </option>
	    {% endfor %}
	  </select>
	  <input type="submit" value="Run Task">
	</form> 

mysite/getData/templates/getData/set_num_boxes.html
<form action="{% url 'getData:write_num_boxes' %}" method="post">
{% csrf_token %}
    How Many Boxes: <input type="text" name="newNumBoxes" "value=0" />
		    <input type="submit" value="submit" />
</form>

mysite/getData/templates/getData/store_data_form.html
<form action="{% url 'getData:write_PiData' box_nr %}" method="post"> 
{% csrf_token %}
	 <input type="text" name="piData" "value=None" />
	 <input type="submit" value="send">
</form> 

mysite/getData/templates/getData/upload_new_task.html
{% if isOnline %}

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    <input type="file" name="sentFile" />
    <input type="submit" name="submit" value="Upload" />
</form>

{% endif %}

{% if not isOnline %}

The box is not online so it is not possible to upload to :(

{% endif%}